# Generated by Django 4.1.5 on 2023-01-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tapp', '0002_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='desc',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='img',
            new_name='imgs',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='name',
            new_name='names',
        ),
    ]
