# Generated by Django 4.1.5 on 2023-01-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tapp', '0003_rename_desc_picture_descr_rename_img_picture_imgs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='descr',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='imgs',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='names',
            new_name='name',
        ),
    ]
