# Generated by Django 4.1.5 on 2023-01-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tapp', '0004_rename_descr_picture_desc_rename_imgs_picture_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='name',
            new_name='head',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='desc',
            new_name='para',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='img',
            new_name='pic',
        ),
    ]
